apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-login-hpa
  namespace: brewingstand
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-login-deployment
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 3  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale when CPU utilization exceeds 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70